/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.CommunityDirectoryH;
import model.CommunityDirectoryHos;
import model.DoctorDirectory;
import model.HospitalDoctorDirectory;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author Deepak Sawalka
 */
public class CommunityJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CommunityJFrame
     */
    PatientDirectory patientHistory;
    PersonDirectory personHistory;
    CommunityDirectoryH communityHistoryH;
    CommunityDirectoryHos communityHistoryHos;
    DoctorDirectory doctorHistory;
    HospitalDoctorDirectory doctorHospitalHistory;
    public CommunityJFrame( PersonDirectory personHistory,PatientDirectory patientHistory,CommunityDirectoryH communityHistoryH,CommunityDirectoryHos communityHistoryHos) {
        initComponents();
        this.communityHistoryH=communityHistoryH;
        this.communityHistoryHos=communityHistoryHos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitpane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        housebtnc = new javax.swing.JButton();
        hospitalbtnc = new javax.swing.JButton();
        backbtnc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        housebtnc.setText("House");
        housebtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housebtncActionPerformed(evt);
            }
        });

        hospitalbtnc.setText("Hospital");
        hospitalbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalbtncActionPerformed(evt);
            }
        });

        backbtnc.setText("<<");
        backbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalbtnc)
                    .addComponent(housebtnc)
                    .addComponent(backbtnc))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backbtnc)
                .addGap(124, 124, 124)
                .addComponent(housebtnc)
                .addGap(85, 85, 85)
                .addComponent(hospitalbtnc)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        splitpane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        splitpane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtncActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginJFrame loginjframe=new LoginJFrame( personHistory, patientHistory,communityHistoryH,communityHistoryHos,doctorHistory, doctorHospitalHistory);
        loginjframe.setVisible(true);
    }//GEN-LAST:event_backbtncActionPerformed

    private void housebtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housebtncActionPerformed
        // TODO add your handling code here:
        HouseJPanel housePanel=new HouseJPanel(communityHistoryH,communityHistoryHos);
        splitpane.setRightComponent(housePanel);
    }//GEN-LAST:event_housebtncActionPerformed

    private void hospitalbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalbtncActionPerformed
        // TODO add your handling code here:
        HospitalJPanel hospitalPanel=new HospitalJPanel(communityHistoryH,communityHistoryHos,doctorHospitalHistory);
        splitpane.setRightComponent(hospitalPanel);
    }//GEN-LAST:event_hospitalbtncActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtnc;
    private javax.swing.JButton hospitalbtnc;
    private javax.swing.JButton housebtnc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane splitpane;
    // End of variables declaration//GEN-END:variables
}
