/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.DoctorDirectory;

/**
 *
 * @author Deepak Sawalka
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    DoctorDirectory doctorHistory;
    public DoctorJPanel(DoctorDirectory doctorHistory) {
        initComponents();
        this.doctorHistory=doctorHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        toppanel = new javax.swing.JPanel();
        createdocbtn = new javax.swing.JButton();
        viewdocbtn = new javax.swing.JButton();
        bottompanel = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        createdocbtn.setText("Create");
        createdocbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdocbtnActionPerformed(evt);
            }
        });

        viewdocbtn.setText("View");
        viewdocbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdocbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(createdocbtn)
                .addGap(73, 73, 73)
                .addComponent(viewdocbtn)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdocbtn)
                    .addComponent(viewdocbtn))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(toppanel);

        javax.swing.GroupLayout bottompanelLayout = new javax.swing.GroupLayout(bottompanel);
        bottompanel.setLayout(bottompanelLayout);
        bottompanelLayout.setHorizontalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        bottompanelLayout.setVerticalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(bottompanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createdocbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdocbtnActionPerformed
        // TODO add your handling code here:
        CreateDoctorJPanel createdoctorjpanel=new CreateDoctorJPanel(doctorHistory);
        jSplitPane1.setBottomComponent(createdoctorjpanel);
    }//GEN-LAST:event_createdocbtnActionPerformed

    private void viewdocbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdocbtnActionPerformed
        // TODO add your handling code here:
        ViewDoctorJPanel viewdoctorjpanel=new ViewDoctorJPanel(doctorHistory);
        jSplitPane1.setBottomComponent(viewdoctorjpanel);
    }//GEN-LAST:event_viewdocbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottompanel;
    private javax.swing.JButton createdocbtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel toppanel;
    private javax.swing.JButton viewdocbtn;
    // End of variables declaration//GEN-END:variables
}
