/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.CommunityDirectoryH;
import model.CommunityDirectoryHos;
import model.DoctorDirectory;
import model.HospitalDoctorDirectory;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author Deepak Sawalka
 */
public class HospitalAdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HospitalJFrame
     */
    PersonDirectory personHistory;
    PatientDirectory patientHistory;
    CommunityDirectoryH communityHistoryH;
    CommunityDirectoryHos communityHistoryHos;
    DoctorDirectory doctorHistory;
    HospitalDoctorDirectory doctorHospitalHistory;
    public HospitalAdminJFrame(CommunityDirectoryHos communityHistoryHos,DoctorDirectory doctorHistory) {
        initComponents();
        this.communityHistoryHos=communityHistoryHos;
        this.doctorHistory=doctorHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        toppanel = new javax.swing.JPanel();
        hospitalbtn = new javax.swing.JButton();
        doctorbtn = new javax.swing.JButton();
        patientbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        bottompanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        toppanel.setPreferredSize(new java.awt.Dimension(846, 200));

        hospitalbtn.setText("Hospital");
        hospitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalbtnActionPerformed(evt);
            }
        });

        doctorbtn.setText("Doctor");
        doctorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorbtnActionPerformed(evt);
            }
        });

        patientbtn.setText("Patient");

        backbtn.setText("<<");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(hospitalbtn)
                .addGap(18, 18, 18)
                .addComponent(doctorbtn)
                .addGap(18, 18, 18)
                .addComponent(patientbtn)
                .addContainerGap(518, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addGap(98, 98, 98))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalbtn)
                    .addComponent(doctorbtn)
                    .addComponent(patientbtn))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(toppanel);

        bottompanel.setPreferredSize(new java.awt.Dimension(704, 500));

        javax.swing.GroupLayout bottompanelLayout = new javax.swing.GroupLayout(bottompanel);
        bottompanel.setLayout(bottompanelLayout);
        bottompanelLayout.setHorizontalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );
        bottompanelLayout.setVerticalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(bottompanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalbtnActionPerformed
        // TODO add your handling code here:
        HospitalJPanel hospitalPanel=new HospitalJPanel(communityHistoryH,communityHistoryHos,doctorHospitalHistory);
        jSplitPane1.setBottomComponent(hospitalPanel);
    }//GEN-LAST:event_hospitalbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginJFrame loginjframe=new LoginJFrame(personHistory, patientHistory,communityHistoryH,communityHistoryHos,doctorHistory, doctorHospitalHistory);
        loginjframe.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void doctorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorbtnActionPerformed
        // TODO add your handling code here:
      
        DoctorJPanel doctorJPanel=new DoctorJPanel(doctorHistory);
        jSplitPane1.setBottomComponent(doctorJPanel);
        
    }//GEN-LAST:event_doctorbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JPanel bottompanel;
    private javax.swing.JButton doctorbtn;
    private javax.swing.JButton hospitalbtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton patientbtn;
    private javax.swing.JPanel toppanel;
    // End of variables declaration//GEN-END:variables
}
