/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CommunityH;
import model.CommunityDirectoryH;
import model.CommunityDirectoryHos;
import model.CommunityHos;
import model.HospitalDoctor;
import model.HospitalDoctorDirectory;

/**
 *
 * @author Deepak Sawalka
 */
public class HospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalJPanel
     */
    CommunityDirectoryH communityHistoryH;
    CommunityDirectoryHos communityHistoryHos;
    HospitalDoctorDirectory doctorHospitalHistory;
    public HospitalJPanel(CommunityDirectoryH communityHistoryH,CommunityDirectoryHos communityHistoryHos,HospitalDoctorDirectory doctorHospitalHistory) {
        initComponents();
        this.communityHistoryH=communityHistoryH;
        this.communityHistoryHos=communityHistoryHos;
        this.doctorHospitalHistory=doctorHospitalHistory;
        populateTableCommHos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelblhos = new javax.swing.JLabel();
        addresslblhos = new javax.swing.JLabel();
        zipcodelblhos = new javax.swing.JLabel();
        citylblhos = new javax.swing.JLabel();
        nametxthos = new javax.swing.JTextField();
        addresstxthos = new javax.swing.JTextField();
        zipcodetxthos = new javax.swing.JTextField();
        citytxthos = new javax.swing.JTextField();
        createbtnhos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hospitaldetailstbl = new javax.swing.JTable();
        updatebtnhos = new javax.swing.JButton();
        deletebtnhos = new javax.swing.JButton();
        searchbtnhos = new javax.swing.JLabel();
        searchtxthos = new javax.swing.JTextField();

        namelblhos.setText("Name");

        addresslblhos.setText("Address");

        zipcodelblhos.setText("ZipCode");

        citylblhos.setText("City");

        createbtnhos.setText("Create");
        createbtnhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnhosActionPerformed(evt);
            }
        });

        hospitaldetailstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Address", "ZipCode", "City"
            }
        ));
        hospitaldetailstbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hospitaldetailstblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hospitaldetailstbl);

        updatebtnhos.setText("Update");

        deletebtnhos.setText("Delete");
        deletebtnhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnhosActionPerformed(evt);
            }
        });

        searchbtnhos.setText("Search");

        searchtxthos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxthosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zipcodelblhos)
                            .addComponent(citylblhos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zipcodetxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citytxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(createbtnhos)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchbtnhos)
                        .addGap(27, 27, 27)
                        .addComponent(searchtxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namelblhos)
                            .addComponent(addresslblhos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addresstxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxthos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(updatebtnhos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletebtnhos))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namelblhos)
                            .addComponent(zipcodelblhos)
                            .addComponent(nametxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipcodetxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addresslblhos)
                            .addComponent(addresstxthos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(citylblhos)
                                .addComponent(citytxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(createbtnhos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtxthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtnhos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtnhos)
                    .addComponent(deletebtnhos))
                .addGap(77, 77, 77))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchtxthosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxthosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxthosActionPerformed

    private void createbtnhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnhosActionPerformed
        // TODO add your handling code here:
        String hospitalname= nametxthos.getText();
        String hospitaladdress= addresstxthos.getText();
        String hcity= citytxthos.getText();
        int hzipcode= Integer.parseInt(zipcodetxthos.getText());
       
        
        CommunityHos cHos =communityHistoryHos.addNewCommunityHos();
        cHos.setHospitalname(hospitalname);
        cHos.setHospitaladdress(hospitaladdress);
        cHos.setCity(hcity);
        cHos.setZipcode(hzipcode);
        JOptionPane.showMessageDialog(this, "Registered Successfully!!");
        
        nametxthos.setText("");
        addresstxthos.setText("");
        citytxthos.setText("");
        zipcodetxthos.setText("");
    }//GEN-LAST:event_createbtnhosActionPerformed

    private void hospitaldetailstblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospitaldetailstblMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex=hospitaldetailstbl.getSelectedRow();
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Data not Found");
             return;}
             
          DefaultTableModel model=(DefaultTableModel) hospitaldetailstbl.getModel();
          CommunityHos selectedCommunityHos=(CommunityHos ) model.getValueAt(selectedRowIndex, 0);
          
          nametxthos.setText(selectedCommunityHos.getHospitalname());
          addresstxthos.setText(selectedCommunityHos.getHospitaladdress());
          zipcodetxthos.setText(String.valueOf(selectedCommunityHos.getZipcode()));
          citytxthos.setText(selectedCommunityHos.getCity());
    }//GEN-LAST:event_hospitaldetailstblMouseClicked

    private void deletebtnhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnhosActionPerformed
        // TODO add your handling code here:
        int i=hospitaldetailstbl.getSelectedRow();
        if (i<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
             return;}
             
          DefaultTableModel model=(DefaultTableModel) hospitaldetailstbl.getModel();
          CommunityHos selectedCommunityHos=(CommunityHos) model.getValueAt(i, 0);
          
          communityHistoryHos.deleteCommunityHos(selectedCommunityHos);
          JOptionPane.showMessageDialog(this, "Hospital Records Deleted Successfully!!");
          populateTableCommHos();
           nametxthos.setText("");
           addresstxthos.setText("");
           zipcodetxthos.setText("");
           citytxthos.setText("");
    }//GEN-LAST:event_deletebtnhosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslblhos;
    private javax.swing.JTextField addresstxthos;
    private javax.swing.JLabel citylblhos;
    private javax.swing.JTextField citytxthos;
    private javax.swing.JButton createbtnhos;
    private javax.swing.JButton deletebtnhos;
    private javax.swing.JTable hospitaldetailstbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namelblhos;
    private javax.swing.JTextField nametxthos;
    private javax.swing.JLabel searchbtnhos;
    private javax.swing.JTextField searchtxthos;
    private javax.swing.JButton updatebtnhos;
    private javax.swing.JLabel zipcodelblhos;
    private javax.swing.JTextField zipcodetxthos;
    // End of variables declaration//GEN-END:variables

private void populateTableCommHos() {
        DefaultTableModel model=(DefaultTableModel) hospitaldetailstbl.getModel();
        model.setRowCount(0);
        
        for (CommunityHos cHos : communityHistoryHos.getCommunityHistoryHos())
        {
            Object[] col=new Object[4];
            col[0]= cHos;
            col[1]= cHos.getHospitaladdress();
            col[2]=cHos.getZipcode();
            col[3]=cHos.getCity();
                   
            model.addRow(col);
            
        }
}

}




