/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CommunityDirectoryH;
import model.CommunityDirectoryHos;
import model.Doctor;
import model.DoctorDirectory;
import model.HospitalDoctor;
import model.HospitalDoctorDirectory;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author Deepak Sawalka
 */
public class HospitalDoctorJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HospitalDoctorJFrame
     */
    PersonDirectory personHistory;
    PatientDirectory patientHistory;
    CommunityDirectoryH communityHistoryH;
        CommunityDirectoryHos communityHistoryHos;
    HospitalDoctorDirectory doctorHospitalHistory;
    DoctorDirectory doctorHistory;
    
    public HospitalDoctorJFrame( PersonDirectory personHistory,PatientDirectory patientHistory,CommunityDirectoryH communityHistoryH,CommunityDirectoryHos communityHistoryHos,DoctorDirectory doctorHistory,HospitalDoctorDirectory doctorHospitalHistory) {
        initComponents();
        this.personHistory=personHistory;
        this.patientHistory= patientHistory;
        this.communityHistoryH=communityHistoryH;
        this.communityHistoryHos=communityHistoryHos;
        this.doctorHistory=doctorHistory;
        this.doctorHospitalHistory=doctorHospitalHistory;
        populateTableHd();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        citytxthd = new javax.swing.JTextField();
        namelblhh = new javax.swing.JLabel();
        addresslblhd = new javax.swing.JLabel();
        zipcodelblhd = new javax.swing.JLabel();
        citylblhd = new javax.swing.JLabel();
        nametxthd = new javax.swing.JTextField();
        addresstxthd = new javax.swing.JTextField();
        zipcodetxthd = new javax.swing.JTextField();
        namecdoclblhd = new javax.swing.JLabel();
        degreecdoctxthd = new javax.swing.JTextField();
        degreecdoclblhd = new javax.swing.JLabel();
        specialitycdoctxthd = new javax.swing.JTextField();
        experiencecdoctxthd = new javax.swing.JTextField();
        contactnocdoclblhd = new javax.swing.JLabel();
        specialitycdoclblhd = new javax.swing.JLabel();
        emailidcdoclblhd = new javax.swing.JLabel();
        experiencecdoclblhd = new javax.swing.JLabel();
        gendercdoclblhd = new javax.swing.JLabel();
        namecdoctxthd = new javax.swing.JTextField();
        gendercdoctxthd = new javax.swing.JTextField();
        emailidcdoctxthd = new javax.swing.JTextField();
        contactnocdoctxthd = new javax.swing.JTextField();
        availabilitylblhd = new javax.swing.JLabel();
        availabilitytxthd = new javax.swing.JTextField();
        createbtnhd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hospitaldoctordetailstbl = new javax.swing.JTable();
        updatebtnhd = new javax.swing.JButton();
        deletebtnhd = new javax.swing.JButton();
        backbtnhd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namelblhh.setText("Hospital Name");

        addresslblhd.setText("Hospital Address");

        zipcodelblhd.setText("ZipCode");

        citylblhd.setText("City");

        namecdoclblhd.setText("Doctor Name");

        degreecdoclblhd.setText("Degree");

        contactnocdoclblhd.setText("Contact No");

        specialitycdoclblhd.setText("Speciality");

        emailidcdoclblhd.setText("Email ID");

        experiencecdoclblhd.setText("Experience");

        gendercdoclblhd.setText("Gender");

        availabilitylblhd.setText("Availibility");

        createbtnhd.setText("Create");
        createbtnhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnhdActionPerformed(evt);
            }
        });

        hospitaldoctordetailstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Address", "ZipCode", "City", "Doctor Name", "gender", "Email ID", "Contact No", "Degree", "Speciality", "Experience", "Availibility"
            }
        ));
        jScrollPane1.setViewportView(hospitaldoctordetailstbl);

        updatebtnhd.setText("Update");

        deletebtnhd.setText("Delete");

        backbtnhd.setText("<<");
        backbtnhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnhdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(541, 541, 541)
                .addComponent(createbtnhd)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citylblhd)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(namelblhh)
                            .addGap(37, 37, 37)
                            .addComponent(nametxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addresslblhd)
                                .addComponent(zipcodelblhd))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zipcodetxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addresstxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(citytxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 552, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(specialitycdoclblhd)
                                    .addComponent(degreecdoclblhd))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(degreecdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(specialitycdoctxthd)
                                        .addGap(28, 28, 28))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(availabilitylblhd)
                                        .addGap(18, 18, 18)
                                        .addComponent(availabilitytxthd))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(experiencecdoclblhd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(experiencecdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailidcdoclblhd)
                                    .addComponent(contactnocdoclblhd))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactnocdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailidcdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(namecdoclblhd)
                                    .addGap(28, 28, 28)
                                    .addComponent(namecdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(gendercdoclblhd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gendercdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(updatebtnhd)
                        .addGap(88, 88, 88)
                        .addComponent(deletebtnhd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(backbtnhd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gendercdoclblhd)
                            .addComponent(gendercdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(specialitycdoclblhd)
                            .addComponent(specialitycdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactnocdoclblhd)
                            .addComponent(contactnocdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(backbtnhd)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(availabilitytxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(nametxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(namecdoclblhd)
                                                .addComponent(namecdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(namelblhh))
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(addresslblhd)
                                            .addComponent(addresstxthd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(degreecdoclblhd)
                                            .addComponent(degreecdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(89, 89, 89)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(zipcodelblhd)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(zipcodetxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailidcdoclblhd)
                                        .addComponent(emailidcdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(experiencecdoclblhd)
                                        .addComponent(experiencecdoctxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(citylblhd)
                                            .addComponent(citytxthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(availabilitylblhd)))))))
                .addGap(59, 59, 59)
                .addComponent(createbtnhd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebtnhd)
                    .addComponent(updatebtnhd))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createbtnhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnhdActionPerformed
        // TODO add your handling code here:
        
        String hospitalname= nametxthd.getText();
        String hospitaladdress= addresstxthd.getText();
        int zipcode=Integer.parseInt(zipcodetxthd.getText()) ;
        String city= citytxthd.getText();
        String doctorname= namecdoctxthd.getText();
        String gender = (gendercdoctxthd.getText());
        String emailid= (emailidcdoctxthd.getText());
        long contactno= Long.parseLong(contactnocdoctxthd.getText());
        String degree = (degreecdoctxthd.getText());
        String speciality= (specialitycdoctxthd.getText());
        String experience= (experiencecdoctxthd.getText());
        String availability= (availabilitytxthd.getText());
        
        HospitalDoctor hd =doctorHospitalHistory.addNewHospitalDoctor();
        hd.setHospitalname(hospitalname);
        hd.setHospitaladdress(hospitaladdress);
        hd.setZipcode(zipcode);
        hd.setCity(city);
        hd.setDoctorname(doctorname);
        hd.setGender(gender);
        hd.setEmailid(emailid);
        hd.setContactno(contactno);
        hd.setDegree(degree);
        hd.setSpeciality(speciality);
        hd.setExperience(experience);
        hd.setAvailability(availability);
        JOptionPane.showMessageDialog(this, " Registered Successfully!!");
        
        
        
        nametxthd.setText("");
        addresstxthd.setText("");
        zipcodetxthd.setText("");
        citytxthd.setText("");
        namecdoctxthd.setText("");
        gendercdoctxthd.setText("");
        emailidcdoctxthd.setText("");
        contactnocdoctxthd.setText("");
        degreecdoctxthd.setText("");
        specialitycdoctxthd.setText("");
        experiencecdoctxthd.setText("");
        availabilitytxthd.setText("");
        
    }//GEN-LAST:event_createbtnhdActionPerformed

    private void backbtnhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnhdActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginJFrame loginjframe=new LoginJFrame( personHistory, patientHistory,communityHistoryH,communityHistoryHos,doctorHistory, doctorHospitalHistory);
        loginjframe.setVisible(true);
    }//GEN-LAST:event_backbtnhdActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslblhd;
    private javax.swing.JTextField addresstxthd;
    private javax.swing.JLabel availabilitylblhd;
    private javax.swing.JTextField availabilitytxthd;
    private javax.swing.JButton backbtnhd;
    private javax.swing.JLabel citylblhd;
    private javax.swing.JTextField citytxthd;
    private javax.swing.JLabel contactnocdoclblhd;
    private javax.swing.JTextField contactnocdoctxthd;
    private javax.swing.JButton createbtnhd;
    private javax.swing.JLabel degreecdoclblhd;
    private javax.swing.JTextField degreecdoctxthd;
    private javax.swing.JButton deletebtnhd;
    private javax.swing.JLabel emailidcdoclblhd;
    private javax.swing.JTextField emailidcdoctxthd;
    private javax.swing.JLabel experiencecdoclblhd;
    private javax.swing.JTextField experiencecdoctxthd;
    private javax.swing.JLabel gendercdoclblhd;
    private javax.swing.JTextField gendercdoctxthd;
    private javax.swing.JTable hospitaldoctordetailstbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namecdoclblhd;
    private javax.swing.JTextField namecdoctxthd;
    private javax.swing.JLabel namelblhh;
    private javax.swing.JTextField nametxthd;
    private javax.swing.JLabel specialitycdoclblhd;
    private javax.swing.JTextField specialitycdoctxthd;
    private javax.swing.JButton updatebtnhd;
    private javax.swing.JLabel zipcodelblhd;
    private javax.swing.JTextField zipcodetxthd;
    // End of variables declaration//GEN-END:variables

private void populateTableHd() {
        DefaultTableModel model=(DefaultTableModel) hospitaldoctordetailstbl.getModel();
        model.setRowCount(0);
        
        for (HospitalDoctor hd : doctorHospitalHistory.getDoctorHospitalHistory())
        {
            Object[] col=new Object[12];
            col[0]= hd;
            col[1]= hd.getHospitaladdress();
            col[2]= hd.getZipcode();
            col[3]= hd.getCity();
            col[4]= hd.getDoctorname();
            col[5]= hd.getGender();
            col[6]= hd.getEmailid();
            col[7]= hd.getContactno();
            col[8]= hd.getDegree();
            col[9]= hd.getSpeciality();
            col[10]= hd.getExperience();
            col[11]= hd.getAvailability();
             
            
            model.addRow(col);
            
        }
}


}
