/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author Deepak Sawalka
 */
public class SystemJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SystemJFrame
     */
    PersonDirectory personHistory;
    PatientDirectory patientHistory;
    public SystemJFrame(PersonDirectory personHistory,PatientDirectory patientHistory) {
        initComponents();
        this.personHistory=personHistory;
        this.patientHistory=patientHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        persondetailsbtn = new javax.swing.JButton();
        patientdetailsbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        persondetailsbtn.setText("Person Details");
        persondetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persondetailsbtnActionPerformed(evt);
            }
        });

        patientdetailsbtn.setText("Patient Details");
        patientdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientdetailsbtnActionPerformed(evt);
            }
        });

        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(persondetailsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(patientdetailsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbtn)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logoutbtn)
                .addGap(58, 58, 58)
                .addComponent(persondetailsbtn)
                .addGap(73, 73, 73)
                .addComponent(patientdetailsbtn)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void persondetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persondetailsbtnActionPerformed
        // TODO add your handling code here:
        PersonDirectoryJFrame personDirectoryJFrame=new PersonDirectoryJFrame(personHistory,patientHistory);
        personDirectoryJFrame.setVisible(true);
    }//GEN-LAST:event_persondetailsbtnActionPerformed

    private void patientdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientdetailsbtnActionPerformed
        // TODO add your handling code here:
        PatientDirectoryJFrame patientDirectoryJFrame=new PatientDirectoryJFrame(personHistory,patientHistory);
        patientDirectoryJFrame.setVisible(true);
    }//GEN-LAST:event_patientdetailsbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        LoginJFrame loginjframe=new LoginJFrame( personHistory, patientHistory);
        loginjframe.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton patientdetailsbtn;
    private javax.swing.JButton persondetailsbtn;
    // End of variables declaration//GEN-END:variables
}
