/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Doctor;
import model.DoctorDirectory;
import model.Patient;

/**
 *
 * @author Deepak Sawalka
 */
public class ViewDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDoctorJPanel
     */
    DoctorDirectory doctorHistory;
    public ViewDoctorJPanel(DoctorDirectory doctorHistory) {
        initComponents();
        this.doctorHistory=doctorHistory;
        populateTableVDoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewdoctordetailstbl = new javax.swing.JTable();
        gendervdoclbl = new javax.swing.JLabel();
        namevdoclbl = new javax.swing.JLabel();
        emailidvdoclbl = new javax.swing.JLabel();
        experiencevdoclbl = new javax.swing.JLabel();
        specialityvdoclbl = new javax.swing.JLabel();
        degreevdoclbl = new javax.swing.JLabel();
        contactnovdoclbl = new javax.swing.JLabel();
        namevdoctxt = new javax.swing.JTextField();
        gendervdoctxt = new javax.swing.JTextField();
        degreevdoctxt = new javax.swing.JTextField();
        emailidvdoctxt = new javax.swing.JTextField();
        experiencevdoctxt = new javax.swing.JTextField();
        contactnovdoctxt = new javax.swing.JTextField();
        specialityvdoctxt = new javax.swing.JTextField();
        deletevdocbtn = new javax.swing.JButton();
        updatevdocbtn = new javax.swing.JButton();

        viewdoctordetailstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Email Id", "Contact No", "Degree", "Speciality", "Experience"
            }
        ));
        viewdoctordetailstbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewdoctordetailstblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewdoctordetailstbl);

        gendervdoclbl.setText("Gender");

        namevdoclbl.setText("Name");

        emailidvdoclbl.setText("Email Id");

        experiencevdoclbl.setText("Experience");

        specialityvdoclbl.setText("Speciality");

        degreevdoclbl.setText("Degree");

        contactnovdoclbl.setText("Contact No");

        specialityvdoctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityvdoctxtActionPerformed(evt);
            }
        });

        deletevdocbtn.setText("Delete");
        deletevdocbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevdocbtnActionPerformed(evt);
            }
        });

        updatevdocbtn.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gendervdoclbl, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namevdoclbl)
                            .addComponent(namevdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gendervdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailidvdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactnovdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactnovdoclbl)
                            .addComponent(emailidvdoclbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(experiencevdoclbl)
                                .addGap(36, 36, 36)
                                .addComponent(experiencevdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updatevdocbtn)
                                .addGap(52, 52, 52)
                                .addComponent(deletevdocbtn)))))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(degreevdoclbl)
                    .addComponent(degreevdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialityvdoclbl)
                    .addComponent(specialityvdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatevdocbtn)
                    .addComponent(deletevdocbtn))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namevdoclbl)
                    .addComponent(emailidvdoclbl)
                    .addComponent(degreevdoclbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namevdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailidvdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degreevdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gendervdoclbl)
                    .addComponent(contactnovdoclbl)
                    .addComponent(specialityvdoclbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gendervdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contactnovdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(specialityvdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(experiencevdoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(experiencevdoclbl))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void specialityvdoctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityvdoctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityvdoctxtActionPerformed

    private void viewdoctordetailstblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewdoctordetailstblMouseClicked
        // TODO add your handling code here:
        
        int selectedRowIndex=viewdoctordetailstbl.getSelectedRow();
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Data not Found");
             return;}
             
          DefaultTableModel model=(DefaultTableModel) viewdoctordetailstbl.getModel();
          Doctor selectedDoctor=(Doctor) model.getValueAt(selectedRowIndex, 0);
          
          namevdoctxt.setText(selectedDoctor.getName());
          gendervdoctxt.setText(selectedDoctor.getGender());
          emailidvdoctxt.setText(selectedDoctor.getEmailid());
          contactnovdoctxt.setText(String.valueOf(selectedDoctor.getContactno()));
          degreevdoctxt.setText(selectedDoctor.getDegree());
          specialityvdoctxt.setText(selectedDoctor.getSpeciality());
          experiencevdoctxt.setText(selectedDoctor.getExperience());
          
          
    }//GEN-LAST:event_viewdoctordetailstblMouseClicked

    private void deletevdocbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevdocbtnActionPerformed
        // TODO add your handling code here:
         int i=viewdoctordetailstbl.getSelectedRow();
        if (i<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
             return;}
             
          DefaultTableModel model=(DefaultTableModel) viewdoctordetailstbl.getModel();
          Doctor selectedDoctor=(Doctor) model.getValueAt(i, 0);
          
          doctorHistory.deleteDoctor(selectedDoctor);
          JOptionPane.showMessageDialog(this, "Doctor Records Deleted Successfully!!");
          populateTableVDoc();
         namevdoctxt.setText("");
        gendervdoctxt.setText("");
        emailidvdoctxt.setText("");
        contactnovdoctxt.setText("");
        degreevdoctxt.setText("");
        specialityvdoctxt.setText("");
        experiencevdoctxt.setText("");
    }//GEN-LAST:event_deletevdocbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactnovdoclbl;
    private javax.swing.JTextField contactnovdoctxt;
    private javax.swing.JLabel degreevdoclbl;
    private javax.swing.JTextField degreevdoctxt;
    private javax.swing.JButton deletevdocbtn;
    private javax.swing.JLabel emailidvdoclbl;
    private javax.swing.JTextField emailidvdoctxt;
    private javax.swing.JLabel experiencevdoclbl;
    private javax.swing.JTextField experiencevdoctxt;
    private javax.swing.JLabel gendervdoclbl;
    private javax.swing.JTextField gendervdoctxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namevdoclbl;
    private javax.swing.JTextField namevdoctxt;
    private javax.swing.JLabel specialityvdoclbl;
    private javax.swing.JTextField specialityvdoctxt;
    private javax.swing.JButton updatevdocbtn;
    private javax.swing.JTable viewdoctordetailstbl;
    // End of variables declaration//GEN-END:variables

    private void populateTableVDoc() {
        DefaultTableModel model=(DefaultTableModel) viewdoctordetailstbl.getModel();
        model.setRowCount(0);
        
        for (Doctor d  : doctorHistory.getDoctorHistory())
        {
            Object[] col=new Object[7];
            col[0]= d;
            col[1]= d.getGender();
            col[2]= d.getEmailid();
            col[3]= d.getContactno();
            col[4]= d.getDegree();
            col[5]= d.getSpeciality();
            col[6]= d.getExperience();
            
           
                   
            model.addRow(col);
            
        }
}






}
