/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Deepak Sawalka
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/connector";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    int q,i,id,deleteItem;
    public Patient() {
        initComponents();
    }
     public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from patientdetails");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
         
         while (rs.next())
         {
            Vector columnData = new Vector();
            
            for(i=1;i<=q;i++)
            {
                columnData.add(rs.getString("Date"));
                columnData.add(rs.getString("MaritalStatus"));
                columnData.add(rs.getString("Insurance"));
                columnData.add(rs.getString("Allergies"));
                columnData.add(rs.getString("EmergencyContact"));
                columnData.add(rs.getString("MedicalHistory"));
                columnData.add(rs.getString("Symptoms"));
                
                
            }
            
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }
    
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelblpat = new javax.swing.JLabel();
        agelblpat = new javax.swing.JLabel();
        genderlblpat = new javax.swing.JLabel();
        contactnolblpat = new javax.swing.JLabel();
        emailidlblpat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        datelblpat = new javax.swing.JLabel();
        datetxtpat = new javax.swing.JTextField();
        maritallblpat = new javax.swing.JLabel();
        insurancelblpat = new javax.swing.JLabel();
        allergieslblpat = new javax.swing.JLabel();
        emergencylblpat = new javax.swing.JLabel();
        medhistlblpat = new javax.swing.JLabel();
        symptomslblpat = new javax.swing.JLabel();
        symptomstxtpat = new javax.swing.JTextField();
        medhisttxtpat = new javax.swing.JTextField();
        emergencytxtpat = new javax.swing.JTextField();
        allergiestxtpat = new javax.swing.JTextField();
        insurancetxtpat = new javax.swing.JTextField();
        maritaltxtpat = new javax.swing.JTextField();
        submitbtnpat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namelblpat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        agelblpat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        genderlblpat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        contactnolblpat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        emailidlblpat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PATIENT INTAKE FORM");

        datelblpat.setText("Date");

        datetxtpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetxtpatActionPerformed(evt);
            }
        });

        maritallblpat.setText("Marital Status");

        insurancelblpat.setText("Insurance (if any)");

        allergieslblpat.setText("Allergies (if any)");

        emergencylblpat.setText("Emergency Contact");

        medhistlblpat.setText("Medical History");

        symptomslblpat.setText("Symptoms");

        emergencytxtpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencytxtpatActionPerformed(evt);
            }
        });

        insurancetxtpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insurancetxtpatActionPerformed(evt);
            }
        });

        submitbtnpat.setText("Submit");
        submitbtnpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnpatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactnolblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailidlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(symptomslblpat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(medhistlblpat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emergencylblpat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allergieslblpat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(insurancelblpat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maritallblpat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(medhisttxtpat, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(datetxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(symptomstxtpat)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(maritaltxtpat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(insurancetxtpat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(allergiestxtpat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emergencytxtpat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(submitbtnpat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addComponent(datetxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(datelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(maritallblpat)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(maritaltxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insurancetxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insurancelblpat))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allergieslblpat)
                            .addComponent(allergiestxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(agelblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contactnolblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emergencylblpat)
                            .addComponent(emergencytxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(emailidlblpat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(medhistlblpat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(medhisttxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symptomstxtpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(symptomslblpat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(submitbtnpat)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datetxtpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetxtpatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetxtpatActionPerformed

    private void insurancetxtpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insurancetxtpatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insurancetxtpatActionPerformed

    private void emergencytxtpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencytxtpatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencytxtpatActionPerformed

    private void submitbtnpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnpatActionPerformed
        // TODO add your handling code here:
        try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("insert into patientdetails(date,maritalstatus,insurance,allergies,emergencycontact,medicalhistory,symptoms)values(?,?,?,?,?,?,?)");
         
         pst.setString(1,datetxtpat.getText());
         pst.setString(2, maritaltxtpat.getText());
         pst.setString(3, insurancetxtpat.getText());       
         pst.setString(4, allergiestxtpat.getText());
         pst.setString(5, emergencytxtpat.getText());
         pst.setString(6, medhisttxtpat.getText());
         pst.setString(7, symptomstxtpat.getText());
         
         
         if(datetxtpat.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
         else if
             (maritaltxtpat.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
             else if
             (insurancetxtpat.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                     
                             else if
             (allergiestxtpat.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                                     else if
             (emergencytxtpat.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                                             else if
             (medhisttxtpat.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                                                     else if
             (symptomstxtpat.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                                                     
         else
         {
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Record Added Successfully");
         upDateDb();
         
         
    }}
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
        }
        
    }//GEN-LAST:event_submitbtnpatActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel agelblpat;
    private javax.swing.JLabel allergieslblpat;
    private javax.swing.JTextField allergiestxtpat;
    public javax.swing.JLabel contactnolblpat;
    private javax.swing.JLabel datelblpat;
    private javax.swing.JTextField datetxtpat;
    public javax.swing.JLabel emailidlblpat;
    private javax.swing.JLabel emergencylblpat;
    private javax.swing.JTextField emergencytxtpat;
    public javax.swing.JLabel genderlblpat;
    private javax.swing.JLabel insurancelblpat;
    private javax.swing.JTextField insurancetxtpat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maritallblpat;
    private javax.swing.JTextField maritaltxtpat;
    private javax.swing.JLabel medhistlblpat;
    private javax.swing.JTextField medhisttxtpat;
    public javax.swing.JLabel namelblpat;
    private javax.swing.JButton submitbtnpat;
    private javax.swing.JLabel symptomslblpat;
    private javax.swing.JTextField symptomstxtpat;
    // End of variables declaration//GEN-END:variables
}
