/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak Sawalka
 */
public class Person extends javax.swing.JFrame {

    /**
     * Creates new form Person
     */
    private static final String username="root"; 
    private static final String password="Rajkumar123#";
    private static final String dataconn="jdbc:mysql://localhost:3306/connector";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    int q,i,deleteItem;
    public Person() {
        initComponents();
    }
    public void upDateDb()
    {
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("select * from persondetails");
         
         rs=pst.executeQuery();
         ResultSetMetaData stData= rs.getMetaData();
         q=stData.getColumnCount();
         
         
         while (rs.next())
         {
            Object[] columnData = new Object[7];
            
            
                
                columnData[0]=rs.getString("Name");
                columnData[1]=rs.getShort("Age");
                columnData[2]=rs.getString("Gender");
                columnData[3]=rs.getString("Contactno");
                columnData[4]=rs.getString("EmailID");
                columnData[5]=rs.getString("Password");
                columnData[6]=rs.getString("ConfirmPassword");
                
               
            
            
         }
         
} 
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
    }
    
    }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelblr = new javax.swing.JLabel();
        agelblr = new javax.swing.JLabel();
        genderlblr = new javax.swing.JLabel();
        emailidtxtr = new javax.swing.JTextField();
        agetxtr = new javax.swing.JTextField();
        gendertxtr = new javax.swing.JTextField();
        emailidlblr = new javax.swing.JLabel();
        contactlblr = new javax.swing.JLabel();
        contactnotxtr = new javax.swing.JTextField();
        passwordlblr = new javax.swing.JLabel();
        confirmpasswordlblr = new javax.swing.JLabel();
        nametxtr = new javax.swing.JTextField();
        submitbtnr = new javax.swing.JButton();
        passwordtxtr = new javax.swing.JPasswordField();
        confirmpasswordtxtr = new javax.swing.JPasswordField();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namelblr.setText("Name");

        agelblr.setText("Age");

        genderlblr.setText("Gender");

        emailidlblr.setText("Email-ID");

        contactlblr.setText("Contact No");

        passwordlblr.setText("Password");

        confirmpasswordlblr.setText("Confirm Password");

        submitbtnr.setText("Submit");
        submitbtnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnrActionPerformed(evt);
            }
        });

        backbtn.setText("<<");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(backbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactnotxtr, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namelblr)
                                .addGap(332, 332, 332)
                                .addComponent(emailidlblr))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nametxtr)
                                        .addGap(125, 125, 125))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(gendertxtr)
                                        .addGap(266, 266, 266))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(agetxtr, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genderlblr)
                                            .addComponent(agelblr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(contactlblr, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(266, 266, 266)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordlblr, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordtxtr, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmpasswordlblr)
                                    .addComponent(confirmpasswordtxtr, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailidtxtr, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(submitbtnr)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelblr)
                    .addComponent(emailidlblr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nametxtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailidtxtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelblr)
                    .addComponent(passwordlblr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agetxtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordtxtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderlblr)
                    .addComponent(confirmpasswordlblr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gendertxtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmpasswordtxtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(contactlblr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactnotxtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(submitbtnr)
                .addGap(56, 56, 56)
                .addComponent(backbtn)
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnrActionPerformed
        // TODO add your handling code here:
        try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
         sqlConn=DriverManager.getConnection(dataconn,username,password);
         pst=sqlConn.prepareStatement("insert into persondetails(Name,Age,Gender,ContactNo,EmailID,Password,ConfirmPassword)values(?,?,?,?,?,?,?)");
         
         pst.setString(1,nametxtr.getText());
         pst.setString(2, agetxtr.getText());
         pst.setString(3, gendertxtr.getText());        
         pst.setString(4, contactnotxtr.getText());
         pst.setString(5, emailidtxtr.getText());
         pst.setString(6, passwordtxtr.getText());
         pst.setString(7, confirmpasswordtxtr.getText());
         
         
         if(nametxtr.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
         else if
             (agetxtr.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
             else if
             (gendertxtr.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                     
                             else if
             (contactnotxtr.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                                     else if
             (emailidtxtr.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                                             else if
             (passwordtxtr.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                                                     else if
             (confirmpasswordtxtr.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Please Enter all the details!!");
         }
                                                     
         else
         {
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this,"Record Added Successfully");
         upDateDb();
         Patient pat=new Patient();
        pat.namelblpat.setText(nametxtr.getText());
        pat.agelblpat.setText(agetxtr.getText());
        pat.genderlblpat.setText(gendertxtr.getText());
        pat.contactnolblpat.setText(contactnotxtr.getText());
        pat.emailidlblpat.setText(emailidtxtr.getText());
        pat.setVisible(true);}
         
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    
        }
        
        
        
  
    }//GEN-LAST:event_submitbtnrActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        new LoginJFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Person().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agelblr;
    private javax.swing.JTextField agetxtr;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel confirmpasswordlblr;
    private javax.swing.JPasswordField confirmpasswordtxtr;
    private javax.swing.JLabel contactlblr;
    private javax.swing.JTextField contactnotxtr;
    private javax.swing.JLabel emailidlblr;
    private javax.swing.JTextField emailidtxtr;
    private javax.swing.JLabel genderlblr;
    private javax.swing.JTextField gendertxtr;
    private javax.swing.JLabel namelblr;
    private javax.swing.JTextField nametxtr;
    private javax.swing.JLabel passwordlblr;
    private javax.swing.JPasswordField passwordtxtr;
    private javax.swing.JButton submitbtnr;
    // End of variables declaration//GEN-END:variables
}
